name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Clean workspace
      run: |
        git reset --hard
        git clean -fdx

    - name: Debug Git Configuration
      run: |
        echo "## Git Version"
        git --version
        echo "## Git Config"
        git config --list
        echo "## Git Status"
        git status

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
      run: |
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "mkdir -p ~/myapp"
        scp -r build/* $SERVER_USER@$SERVER_HOST:~/myapp
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "pm2 restart myapp || pm2 start build/index.js --name myapp"
